/* NEW RANK LIST
WE F. || G DEVELOPER VERIFIED
AL L. || SSS20 DEVELOPER
PH D. || SS16 DEVELOPER VERIFIED
CO F. || SS47 VERIFIED
JO K. || A36 DEVELOPER
AV J. || A49
ST D. || BBB5 DEVELOPER
MA H. || BBB36 DEVELOPER
EM H. || BB18 EXEMPT
HE S. || BB20
PA D. || B6 VERIFIED
AL F. || B38
JA S. || CCC40 EXEMPT
GA B. || CCC50 EXEMPT
NA S. || CC16
*/



/* NEW RANKS
Monty
Hole Digger
The Whacked
Moles
Luxury Moles
F to S in Each
F to FF to FFF to D to DD to DDD.......
50 Spots in Each
4500 Ranks Total
*/
